mac m芯片编译 需要用brew安装的llvm，而不是apple clang 需要用 curl -L "https://cmake.org/files/v3.26/cmake-3.26.5-macos-universal.tar.gz" -o /tmp/cmake.tar.gz 安装的 cmake 3.26；brew 只能安装最新的4.2，和 CMP0042 不兼容 milvus-proto 编译挂了， 删除cmake third_party里的milvus-proto再make重新下载就好了 然后成功到了knowhere: OpenMP: find_package(OpenMP REQUIRED) 换成 add_compile_options(-Xpreprocessor -fopenmp) add_link_options(-lomp) include_directories(/opt/homebrew/opt/libomp/include) link_directories(/opt/homebrew/opt/libomp/lib) simdjson, 主要是 llvm 搞不定一堆 c++ feature 的检查。。。搞了一堆东西终于过了。不确定解法是否正确 faiss如下的错误，不过貌似没影响编译，还没找到解法
CMake Error at /Users/buqianzheng/Documents/milvus/cmake_build/thirdparty/knowhere/knowhere-src/cmake/libs/libfaiss.cmake:238 (target_link_libraries):
  Target "faiss" links to:

    OpenMP::OpenMP_CXX

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  /Users/buqianzheng/Documents/milvus/cmake_build/thirdparty/knowhere/knowhere-src/CMakeLists.txt:140
然后继续编译knowhere，sve挂了 ，还没找到解法

fatal error: error in backend: Calling convention SVE_VectorCall is unsupported on Darwin.
PLEASE submit a bug report to https://github.com/Homebrew/homebrew-core/issues and include the crash backtrace, preprocessed source, and associated run script.

Signed-off-by: Buqian Zheng <zhengbuqian@gmail.com>